### ISSUE TITLE
Missed parameters in the auprc api of oor_benchmark

### ISSUE THREAD

**Issue by cyxss** [MarioniLab/oor_design_reproducibility#22]
In the 'Compure sensitivity in shift OOR state' part of the src/2_simulation_design/oor_design_main/oor_design_mixed.ipynb file, the code use the auprc API as `auprc.auprc(nh_df, return_curve=False, bootstrap_iterations=1000, bootstrap_seed=42) `. 

We met the error 'TypeError: auprc() got an unexpected keyword argument 'bootstrap_iterations'. I checked the oor-benchmark package at https://github.com/MarioniLab/oor_benchmark/blob/e40edad23bbfa7912d5d42ab076fb7b9a7e8e2d7/src/oor_benchmark/metrics/auprc.py, and found no parameters as *bootstrap_iterations* and *bootstrap_seed*.

If I deleted these two parameters, there would be no *CI_upper* and *CI_lower* columns in the auprc_compare dataframe.  How should I change the code to reproduce the barplot?

**Comment by emdann** [comment]
Fixed with https://github.com/MarioniLab/oor_benchmark/commit/e8084a8ada692ab69d674fbef4c9595fb4ab9942
